kind: Service
apiVersion: v1
metadata:
  labels:
    node: node1
  name: nodesvc1
spec:
  selector:
    node: node1
  ports:
  - name: ipc
    port: 21000
    targetPort: 21000
  - name: raftport
    port: 50401
    targetPort: 50401
  - name: rpcport
    port: 22000
    targetPort: 22000
  - name: geth
    port: 9001
    targetPort: 9001
  type: LoadBalancer
